### ISSUE TITLE
Repository size is quite large

### ISSUE THREAD

**Issue by MagedSaeed** [ARBML/Calliar#11]
The repo size is quite large. I suggest moving the dataset-related materials to another source. Either Google storage bucket or even goole drive. What do you think @zaidalyafeai ?

**Comment by zaidalyafeai** [comment]
Yeah, let us move it to a bucket.

**Comment by zaidalyafeai** [comment]
https://github.com/ARBML/Calliar/pull/16 resolves the problem

**Comment by zaidalyafeai** [comment]
Also https://github.com/ARBML/Calliar/pull/17
