### ISSUE TITLE
Pre-commit Utilization

### ISSUE THREAD

**Issue by yousef337** [ARBML/Calliar#3]
# Description 
Introducing pre-commit to the project would help make the codebase more clean and consistent. An already existed configuration can be utilised in Masader-Webserver

**Comment by zaidalyafeai** [comment]
@yousef337 will you work on this?

**Comment by yousef337** [comment]
@zaidalyafeai since this repo will be dedicated to the dataset, I'm going to utilize pre-commit on the server repo that @MagedSaeed will create.
