### ISSUE TITLE
Codebase refactoring

### ISSUE THREAD

**Issue by yousef337** [ARBML/Calliar#4]
# Codebase Refactoring
I think the repo need some refactoring.

# Group the two main parts of the repo
Currently, the repo contains two different parts, the Calliar main part and Calliar server. As for not, only Calliar server files are grouped under one folder, while the main part is on the first level.
A simple solution would be to group Calliar, except the Calliar server folder, into one folder.

# Group the related parts in the Calliar.
Currently, I can see certain files that can be grouped in order to enhance the quality and maintainability of the repo, e.g, the demos and the dataset.

# Vis.py
The file contains some dead code and can be improved in some aspects.

# Calliar server
## Ignored files
.vscode, __pychase__ and .ipynb_checkpoints need to not be tracked in Github
## The static folder
The files can be grouped if they are similar types.

**Comment by zaidalyafeai** [comment]
@yousef337 I have a couple of ideas, we will disucss on the meeting next Monday :)

**Comment by zaidalyafeai** [comment]
tracked in https://github.com/ARBML/Calliar/pull/12
